EVAKA-FIX: mobile UI tweaks
espoon-voltti/evaka pull request #1158
Opened 2021-07-16 12:00 UTC by hruoho

#### Summary

Add minor CSS tweaks to child's mobile view

-

<img width="408" alt="Screenshot 2021-07-16 at 14 58 54" src="https://user-images.githubusercontent.com/3275771/125944080-c74b7c41-c216-4089-a017-83e4350de81f.png">

2021-07-16 12:19 UTC, mikkopiu requested changes

2021-07-16 12:19 UTC, mikkopiu commented on frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
> +  font-family: Montserrat, 'Open Sans', 'Arial', sans-serif;
Why both Montserrat and Open Sans?

2021-07-16 14:01 UTC, hruoho commented on frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
> +  font-family: Montserrat, 'Open Sans', 'Arial', sans-serif;
```suggestion
  font-family: Montserrat, 'Arial', sans-serif;
```

2021-07-19 07:26 UTC, mikkopiu approved these changes

2021-07-19 10:44 UTC, merged