Add data-qa attributes to help city-specific e2e testing
espoon-voltti/evaka pull request #1384
Opened 2021-09-15 12:19 UTC by apeltola

2021-09-15 13:09 UTC, mikkopiu requested changes

2021-09-15 13:09 UTC, mikkopiu commented on frontend/src/citizen-frontend/applications/editor/AdditionalDetailsSection.tsx
> +              data-qa="diet-info"
Nit: `diet-expanding-info` would be more in line with the other new attributes.

2021-09-15 13:09 UTC, mikkopiu commented on frontend/src/lib-components/molecules/ExpandingInfo.tsx
> +            <InfoContainer data-qa={`${dataQa ?? ''}-text`}>
Wouldn't it be better to leave the whole attribute out if `dataQa` is not set?

2021-09-16 13:32 UTC, reynders approved these changes

2021-09-17 11:58 UTC, mikkopiu approved these changes
LGTM, pushing to CI

2021-09-17 12:10 UTC, mikkopiu commented
@apeltola some lint errors in CI, see status links

2021-09-17 13:52 UTC, merged