Copy files to S3 before deploy
espoon-voltti/evaka pull request #1389
Opened 2021-09-16 09:51 UTC by ilja-git

#### Summary

2021-09-17 14:00 UTC, mikkopiu requested changes

2021-09-20 10:43 UTC, ilja-git commented on .circleci/config.yml
> +          command: replace-credentials
This was copy of the script earlier. Seems that we use it wrongly in two places already.

https://github.com/espoon-voltti/evaka/blob/master/.circleci/config.yml#L503
https://github.com/espoon-voltti/evaka/blob/master/.circleci/config.yml#L704

Fixed in all.

2021-09-20 12:08 UTC, mikkopiu commented on .circleci/config.yml
> +          command: replace-credentials
Ah! I was confused on how that could've ever worked correctly but `--profile` overrides `AWS_*` envs. So in summary, as long as the steps following the invocation of `replace-credentials` (sourced or not) explicitly define `--profile`s -> they work correctly -> sourcing is effectively irrelevant.

2021-09-20 12:10 UTC, mikkopiu commented on .circleci/config.yml
> +          command: replace-credentials
I.e. ignore me

2021-09-20 12:10 UTC, mikkopiu approved these changes

2021-09-20 12:10 UTC, merged