Evaka create citizen subnavigation
espoon-voltti/evaka pull request #1437
Opened 2021-09-27 06:54 UTC by mapehe

#### Summary

2021-09-28 09:07 UTC, Joosakur requested changes

2021-09-28 09:07 UTC, Joosakur commented on frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
> +      applying: 'Ansöker'
has this been checked from somewhere?

2021-09-28 09:07 UTC, Joosakur commented on frontend/src/citizen-frontend/map/MapView.tsx
> +    <MapFullscreenContainer loggedIn={loggedIn}>
![Screenshot 2021-09-28 at 12 05 10](https://user-images.githubusercontent.com/1533854/135057848-c70be89b-7c1f-4084-bbb6-f191e1e74f00.png)
Something wrong with the map. Sometimes that gray area goes away when moving the map but reappears on refresh. No issue when logged out.

2021-09-28 09:17 UTC, Joosakur commented
in the spec there's a gap between the top nav and secondary tabs
![Screenshot 2021-09-28 at 12 11 38](https://user-images.githubusercontent.com/1533854/135058734-aa642596-d407-4610-94d1-1fbf50b2341b.png)

2021-09-29 07:14 UTC, mapehe commented
Thanks for the feedback @Joosakur, suggested some fixes in 0703968.

2021-09-29 08:16 UTC, Joosakur approved these changes

2021-09-29 08:17 UTC, merged