TREV-433 possibility to send fee decisions in advance with configurable date
espoon-voltti/evaka pull request #1849
Opened 2021-12-17 15:11 UTC by apeltola

Made this with env variable for the less amount of hassle in case all cities will take this later on as default way of working.

Also, fixed related test, that had feeDecision id as string instead of a string array.

2021-12-17 15:12 UTC, apeltola commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
> +            it.validFrom.atStartOfDay() > lastPossibleDecisionValidFromDate.atStartOfDay()
Tää on ainakin syytä tsekata, koska aiemmin ei ollut tällaista päivän alkuhetkeen siirtoa.

2021-12-20 08:54 UTC, jaahon requested changes

2021-12-20 08:54 UTC, jaahon commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
> +                Instant.now().plus(Period.ofDays(env.nrOfDaysFeeDecisionCanBeSentInAdvance))
Latest convention to using current time/date is to use `EvakaClock` and its `today()` and `now()` methods to make it easier to mock the current time in tests. So in practice you can add `evakaClock: EvakaClock` to the endpoints parameters.

2021-12-20 08:54 UTC, jaahon commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
> +        lastPossibleDecisionValidFrom: Instant
Seems like this parameter could just be a `LocalDate`.

2021-12-20 08:54 UTC, jaahon commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
> +        val now = Instant.now()
It's preferable to pass current time as a parameter to make mocking easier.

2021-12-20 08:54 UTC, jaahon commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
> +            it.validFrom.atStartOfDay() > lastPossibleDecisionValidFromDate.atStartOfDay()
It doesn't seem like converting `LocalDate`s to `LocalDateTime`s has any benefit here.

2021-12-20 08:54 UTC, jaahon commented on service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
> +        assertEquals(actual.sentAt?.truncatedTo(ChronoUnit.DAYS), nowDate.atStartOfDay().toInstant(ZoneOffset.UTC))
If you used mocked time in this test, you could just do a normal equality check. Like this:

```
val now = HelsinkiDateTime.of(...)
...
val (_, response, _) = http.post("/decisions/confirm")
    .withMockedTime(now)
...
assertEquals(now.toInstant(), actual.sentAt)
```

2021-12-20 08:54 UTC, jaahon commented on service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
> +            JSONObject(response.body().asString("text/json")).getString("errorCode")
Use `objectMapper` instead of `JSONObject` for consistency.

2021-12-22 06:46 UTC, jaahon reviewed
Almost there, just need to fix the imports 😄

2021-12-22 06:46 UTC, jaahon commented on service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
> +            .copy(validDuring = DateRange(clock.today().plusDays(1), clock.today().plusYears(1)))
You don't need `clock` here, you could just use `now.toLocalDate()` instead of `clock.today()`.

2021-12-23 08:35 UTC, Gekkio commented on service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
> +    @SpyBean
Do we really need to use a mock here? :thinking: 
It's a big change, especially since it affects all tests that use `FullApplicationTest`

2022-01-07 07:19 UTC, jaahon approved these changes

2022-01-07 08:25 UTC, merged