EVAKA-4469 edit assistance need decisions first steps
espoon-voltti/evaka pull request #2575
Opened 2022-06-21 06:47 UTC by zch

Includes
- data model and controller for the assistance need decisions
- simple integration test for the controller
- stub for the assistance need decision preview page
- editable form for single assistance need decisions
- edits of the form are not yet persisted
- simple e2e smoketest

2022-06-21 10:02 UTC, reynders requested changes

2022-06-21 12:40 UTC, zch commented on frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts
> +  readonly #decisionMakerSelect = this.page.find(
👍 fixed

2022-06-21 12:43 UTC, zch commented on frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
> +          <FooterContainer>TODO</FooterContainer>
There are notes for all these TODOs on our board and I (or someone else) will get to them. Would you prefer removing all TODO markings from this PR?

2022-06-21 12:55 UTC, zch commented on service/src/main/resources/db/migration/V243__assistance_need_decisions.sql
> +    assistance_need_decision_id uuid not null references assistance_need_decision on delete cascade,
👍 fixed

2022-06-21 12:57 UTC, zch commented on frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
> +              console.log({ hasErrors })
Nice catch. The console.log was not supposed to go in. Error handling is not yet implemented.

2022-06-22 06:27 UTC, reynders commented on frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
> +          <FooterContainer>TODO</FooterContainer>
No need to fix, this is ok

2022-06-22 06:29 UTC, reynders approved these changes

2022-06-22 06:33 UTC, merged