Fix footer
espoon-voltti/evaka pull request #2861
Opened 2022-09-07 13:26 UTC by reynders

#### Summary

2022-09-07 14:42 UTC, jaahon requested changes

2022-09-07 14:42 UTC, jaahon commented on frontend/src/citizen-frontend/navigation/MobileNav.tsx
> +  position: fixed;
Using `position: fixed` means that 60px of content on every page is hidden behind the bottom bar. The problem in messages page is that the `FullHeightContainer` container in `MessagesPage.tsx` has a fixed height so the bottom bar is positioned after container but the actual contents inside the container overflow and are shown under the bottom bar. It seems that removing `height: calc(100vh - ${headerHeightDesktop}px);` fixes it and doesn't have an effect on anything else. It must have been put there for some reason at some point but whatever the reason was it doesn't seem to work anymore.

2022-09-08 04:16 UTC, akheron commented on frontend/src/citizen-frontend/messages/MessagesPage.tsx
> -`
It's not a "full height container" anymore, so you should change the name. Or just use a plain `<div>` instead.

2022-09-08 05:14 UTC, jaahon commented on frontend/src/citizen-frontend/messages/MessagesPage.tsx
> +    <div>
You should still use `lib-components/layout/Container` here.

2022-09-08 05:56 UTC, jaahon approved these changes

2022-09-08 07:04 UTC, merged