Update placement unit name visibility
espoon-voltti/evaka pull request #3585
Opened 2023-05-04 06:36 UTC by patari

#### Summary

Adds placement unit name to unit supervisor and special education teacher for all placements (not just own units).

2023-05-08 07:52 UTC, akheron requested changes
Does this really need 3 states, or could everyone with access to child's page see the name of the unit?

2023-05-11 12:18 UTC, Gekkio approved these changes

2023-05-12 06:25 UTC, patari commented
> > Does this really need 3 states
> 
> According to spec, yes it does.

Spec changed, unit name is now visible for all unit roles.

2023-05-16 07:28 UTC, akheron approved these changes

2023-05-16 08:11 UTC, merged