add more tests to understand current logic
espoon-voltti/evaka pull request #3696
Opened 2023-06-02 08:32 UTC by Joosakur

#### Summary

2023-08-22 10:20 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
> +    return (partners + otherParents + adultId).toSet()
check fee decisions?

2023-08-23 08:42 UTC, akheron requested changes

2023-08-23 08:42 UTC, akheron commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
> +        WHERE fd.head_of_family_id = ${bind(personId)} OR fd.partner_id = ${bind(personId)} AND fd.status <> 'DRAFT'
This `AND/OR` requires parentheses

2023-08-23 08:43 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
> +        WHERE fd.head_of_family_id = ${bind(personId)} OR fd.partner_id = ${bind(personId)} AND fd.status <> 'DRAFT'
yes, we noticed same 😓 already fixed!

2023-08-23 08:44 UTC, akheron approved these changes

2023-08-23 08:54 UTC, merged