Show (*) and a tooltip on automatically closed staff attendances
espoon-voltti/evaka pull request #4667
Opened 2024-01-25 06:36 UTC by reynders

<img width="332" alt="Screenshot 2024-01-29 at 12 33 17" src="https://github.com/espoon-voltti/evaka/assets/158767/ca8fedb5-8f54-4685-9017-e538906afc40">

2024-01-30 05:57 UTC, reynders commented on frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
> +      {attendance.departedAutomatically ? (
Redundant check for future use of this tooltip for other info too

2024-02-02 11:30 UTC, Joosakur requested changes

2024-02-02 11:30 UTC, Joosakur commented on frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
> +                      </>
I think duplicating the whole thing is unnecessary. AFAIK tooltip is not rendered if tooltip prop is falsy.

```
const attendanceTooltip = attendanceTooltipText(attendance) // undefined if no tooltip
...
                          <Tooltip
                            key={i}
                            tooltip={attendanceTooltip}
                            data-qa="attendance-tooltip"
                          >
                            <AttendanceCell>
                              <AttendanceTime data-qa="arrival-time">
                                {renderTime(attendance.arrived, date)}
                              </AttendanceTime>
                              <AttendanceTime data-qa="departure-time">
                                {renderTime(attendance.departed, date)}
                                {attendanceTooltip ? ' (*)'}
                              </AttendanceTime>
                            </AttendanceCell>
                          </Tooltip>
```

2024-02-02 11:30 UTC, Joosakur commented on frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
> +        <div>{i18n.unit.staffAttendance.departedManually}</div>
Is departedManually ever shown? Below the tooltip is omitted when `!attendance.departedAutomatically`. You can just return undefined here.

2024-02-02 11:30 UTC, Joosakur commented on frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
> +      departedManually: 'Manuaalikatkaistu',
probably not needed

2024-02-06 08:47 UTC, Joosakur commented on frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
>                      ))
```
                    attendancesForToday.map((attendance, i) => {
                      const tooltip = attendanceTooltipText(attendance)
                      return (
                        <Tooltip
                          key={i}
                          tooltip={tooltip}
                          data-qa="attendance-tooltip"
                        >
                          <AttendanceCell>
                            <AttendanceTime data-qa="arrival-time">
                              {renderTime(attendance.arrived, date)}
                            </AttendanceTime>
                            <AttendanceTime data-qa="departure-time">
                              {renderTime(attendance.departed, date)}
                              {tooltip && ' (*)'}
                            </AttendanceTime>
                          </AttendanceCell>
                        </Tooltip>
                      )
                    })
```
This way you aren't duplicating logic and adding another tooltip reason only requires changing the tooltip returning function.

2024-02-06 11:06 UTC, Joosakur approved these changes

2024-02-06 11:14 UTC, merged