[EVAKA-4159] Fix application received email links and update texts
espoon-voltti/evaka pull request #573
Opened 2021-03-09 15:16 UTC by mikkopiu

#### Summary
- Invalid href value (missing protocol) caused links to be output as [link]link instead of being valid links
- Update "application received" email's Finnish and Swedish texts per new spec

2021-03-10 05:13 UTC, massproduction approved these changes

2021-03-10 06:31 UTC, kustaahuhtala requested changes
There will be some additional changes for the texts. I suggest we put them into this PR, too (once we get them).

2021-03-11 09:25 UTC, mikkopiu commented
@kustaahuhtala Updated texts. We can add the English texts when they arrive, in a separate PR.

2021-03-11 10:08 UTC, kustaahuhtala approved these changes

2021-03-11 10:09 UTC, kustaahuhtala commented
It's good now. Maybe in the future we could link directly to decision page on the citizen frontend, but I think we should unify it at the same time everywhere (in decisions etc, too). Nice work 👌

2021-03-11 10:12 UTC, merged