Puuttuvat tulotiedot - raportti
espoon-voltti/evaka pull request #5920
Opened 2024-11-06 07:23 UTC by tahtee

Puuttuvat tulotiedot - raportti

Raportti vanhemmista, joiden tulotiedot ovat vanhentuneet, mutta lapsella on vielä sijoitus aktiivinen.

![image](https://github.com/user-attachments/assets/06dc2b2d-add0-4211-8885-6621fc81ef2d)

2024-11-07 11:28 UTC, kechpaja-at-gofore approved these changes

2024-11-07 11:28 UTC, kechpaja-at-gofore commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                AND ie.updated_by = '00000000-0000-0000-0000-000000000000'
Tiedoksi, että updated_by-sarakkeen nimi on nyt muuttunut modified_by:ksi.

2024-11-07 11:41 UTC, Gekkio commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +            .also { Audit.TitaniaReportRead.log() }
TitaniaReport?

2024-11-07 11:41 UTC, Gekkio commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                SELECT DISTINCT pe.id as personId, pe.first_name as firstName, pe.last_name as lastName, ie.valid_from as validFrom, pl.unit_id as daycareId, dg.name as daycareName, ca.id as carearea
Tarvitaanko tässä oikeasti DISTINCTiä 8:lle sarakkeelle? Onko esimerkkiä tilanteesta jossa tulee duplikaatteja?

2024-11-07 11:41 UTC, Gekkio commented on service/src/integrationTest/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReportTest.kt
> +    val testArea = DevCareArea(id = AreaId(UUID.randomUUID()), name = "Test Area", areaCode = 200)
Tässä testissä on monessa paikassa paljon manuaalista ID-generointia (`UUID.randomUUID`). Dev-tyypeissä pitäisi olla defaultit jotka hoitaa tämän, eikä testikoodia tarvitse monimutkaistaa tämmöisellä manuaalipyörittelyllä

2024-11-07 11:41 UTC, Gekkio commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +    val daycareId: String,
String? Eikös tämän tyypin pitäisi olla `DaycareId`? ja alla sama arean kanssa

2024-11-07 11:41 UTC, Gekkio commented on service/src/integrationTest/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReportTest.kt
> +            updatedBy = EvakaUserId(UUID.fromString("00000000-0000-0000-0000-000000000000")),
Tässä olisi parempi käyttää `AuthenticatedUser.SystemInternalUser.evakaUserId` eikä hard-koodata UUID-arvoja, varsinkaan string-muodossa

2024-11-07 13:54 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                AND ie.updated_by = '00000000-0000-0000-0000-000000000000'
onks tää ehto muuten minkä takia että viimeinen päivittänyt on system user?

2024-11-07 14:13 UTC, Joosakur requested changes

2024-11-07 14:13 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                        ON gu.child_id = pl.child_id
Tää `gu.child_id = pl.child_id` on nyt turhaan kahdessa paikassa. Vois laittaa vaan tähän suoraan `gu.child_id = pl.child_id AND daterange(pl.start_date, pl.end_date, '[]') @> ${bind(today)}` niin on myös paremmin heti selvää että joinataan vain yhteen eikä tuu mahdollisesti montaa riviä.

2024-11-07 14:13 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                        ON ie.person_id = gu.guardian_id
Onko join guardian tauluun tarkoituksella jolloin esim sijaishuoltajien puutteelliset tulotiedot jää pois raportilta?

2024-11-07 14:13 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                INNER JOIN daycare dg
`INNER ` on ollut konventiona jättää pois kun on default

2024-11-07 14:13 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +                WHERE ie.effect = 'INCOMPLETE'
onko tarkoitus että raportti listaa **puutteelliset** tulotiedot eikä puuttuvia kuten PR:n otsikossa tai vanhentuneita kuten PR:n kuvauksessa? multa ehkä puuttuu kontekstia mihin tän raportin tarve liittyy tai sitten tää malli on ymmärretty väärin

2024-11-07 14:13 UTC, Joosakur commented on service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
> +    val careareaId: String,
tämä myöskään ei string

2024-11-07 14:13 UTC, Joosakur commented on frontend/src/employee-frontend/components/reports/IncompleteIncomeReport.tsx
> +        {report.isSuccess && (
could probably use `renderResult` instead

2024-11-08 08:13 UTC, tahtee commented
@Joosakur homma valmiina uudelleenkatselmointiin

2024-11-08 09:55 UTC, Joosakur approved these changes

2024-11-08 10:27 UTC, merged