Evaka fix daily note fixes
espoon-voltti/evaka pull request #636
Opened 2021-03-30 06:58 UTC by reynders

#### Summary
- Fix daycare group layout to match UX spec (more space, correct table header alignment)
- Fix daycare daily note group note text to be black, not gray

2021-03-30 07:32 UTC, massproduction commented
Should we also add the group notes to `employee-mobile-frontend/components/attendances/notes/DailyNote.tsx`?

2021-03-31 07:52 UTC, reynders commented
> Should we also add the group notes to `employee-mobile-frontend/components/attendances/notes/DailyNote.tsx`?

Is this ok frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNote.tsx

2021-03-31 08:15 UTC, massproduction commented
If the child has only a group note then the ui will not show the daily note icon in the `ChildListItem` (because the check is just `attendanceChild.dailyNote [...] && (`).

The same thing is with `AttendanceChildPage` where the check for icon colour is `active={child && child.dailyNote ? true : false}`. 

Could we add the check for a group note for both of the se cases?

2021-03-31 08:16 UTC, massproduction commented
We are not showing the number of hours slept in the tooltip in the desktop version of daily note. Just how the child slept.

2021-03-31 08:17 UTC, massproduction requested changes

2021-03-31 08:17 UTC, massproduction commented on frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNote.tsx
>          <div>{i18n.attendances.notes.noNotes}</div>
If the child does not have an daily note the groupNote will not be shown. How about adding the groupNote in different spot?

```suggestion
</FixedSpaceColumn>
      ) : (
        <>
          {groupNote ? (
            <FixedSpaceColumn spacing={'xxs'}>
              <Label>{i18n.attendances.notes.labels.groupNotesHeader}</Label>
              <span>{groupNote.note}</span>
            </FixedSpaceColumn>
          ) : (
            <div>{i18n.attendances.notes.noNotes}</div>
          )}
        </>
```

2021-04-01 08:37 UTC, massproduction approved these changes
🏅

2021-04-01 09:27 UTC, merged