Possibility to hide preschool options from citizen UI
espoon-voltti/evaka pull request #790
Opened 2021-05-04 11:16 UTC by apeltola

#### Summary

2021-05-04 11:23 UTC, akheron requested changes

2021-05-04 11:23 UTC, akheron commented on frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
> +          {featureFlags.preschoolEnabled === true && (
`=== true` is not needed, just `featureFlags.preschoolEnabled` is enough

2021-05-04 11:23 UTC, akheron commented on frontend/src/citizen-frontend/map/SearchSection.tsx
> +          {featureFlags.preschoolEnabled === true && (
Same here

2021-05-04 12:49 UTC, apeltola commented
Also did changes to some places having similar comparison

2021-05-05 04:01 UTC, akheron approved these changes

2021-05-05 06:46 UTC, merged