EVAKA-4190 Received messages view for citizen
espoon-voltti/evaka pull request #857
Opened 2021-05-17 10:42 UTC by kimifoud

#### Summary

Received messages view for citizen based on the new messaging model

2021-05-17 11:32 UTC, akheron requested changes

2021-05-17 11:32 UTC, akheron commented on frontend/src/citizen-frontend/messages/MessagesPage.tsx
> +    [setMessagesState]
`setMessagesState` is not needed in the dependency array, because `useState` callbacks are stable.

2021-05-17 11:32 UTC, akheron commented on frontend/src/citizen-frontend/messages/MessagesPage.tsx
> +          thread.id === thread.id
This comparison is always true

2021-05-17 11:40 UTC, kimifoud commented on frontend/src/citizen-frontend/messages/MessagesPage.tsx
> +          thread.id === thread.id
🤦

2021-05-18 04:03 UTC, akheron approved these changes

2021-05-18 05:44 UTC, merged